version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "3000:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge